---
title: "11-reading-in-data"
output: html_notebook
---

```{r}
library(purrr)
library(tictoc)
library(tidyverse)
library(fs)
library(haven)
library(janitor)
library(assertr)

```

```{r import lookup tables}
questions_cats <-
  read_csv(
    path("lookups", "questions_categories_v1-1.csv"),
    col_types = cols(
      column_name = col_character(),
      question_short_es = col_character(),
      question_short_en = col_character(),
      question_es = col_character(),
      question_en = col_character(),
      category_en = col_character(),
      category_short_en = col_character(),
      category_es = col_character(),
      category_short_es = col_character()
    ),
    locale = locale(encoding = "UTF-8")
  ) %>%
  clean_names() # Yilin, add assertions here.

values_labels <-
  read_csv(
    path("lookups", "values_labels_v1-1.csv"),
    col_types = cols(
      column_name = col_character(),
      value = col_character(),
      label_en = col_character(),
      label_es = col_character(),
      value_recoded = col_character()
    ),
    locale = locale(encoding = "UTF-8")
  ) %>%
  clean_names() 
```


```{r creating country-code lookup}

target_vars <- questions_cats$column_name #unique columns to filter the data by

response_labels <- values_labels %>%
  left_join(questions_cats, by = "column_name") %>%
  select(column_name, question_es, value, value_recoded, label_es)

# Create countries lookup to Add country name into dataframe
countries <- response_labels %>%
  filter(column_name == "pais") %>%
  rename(country = label_es, pais = value) %>%
  select(pais, value_recoded)

```


```{r function to add country to data frame being read in}

# This function checks if country column exists in the dataframe, and if it does then it makes sure that the country matches the country code.  If it doesn't then it adds the country code from the name of file. 
get_country <- function(file, filename){
  # inputs : 
  # file - dataframe to be used
  # filename - the name of the file being imported
  # output : dataframe with correct country as a column
  if("pais" %in% colnames(file)){
    
    pais_in_file <- file$pais %>% unique()
    country_code <- countries %>% 
      filter(pais == pais_in_file) %>% 
      pull(value_recoded)
    
    # print(paste0("Making sure country in data matches country in ", filename))
    # print(substr(filename,1,3))
    # print(file$pais[[1]])
    # print(country_code)
    if(substr(filename,1,3)==country_code){
      cat("pais success... ")
    } else {print(paste0("DOUBLE CHECK COUNTRY IN ",filename))}
    return(file)
  }
  else{
    #print( paste0("Replacing missing country in ", filename))
    
    country_num <- countries %>% 
      filter(value_recoded == substr(filename, 1,3)) %>% 
      pull(pais)
    
    file$pais <- country_num
    cat("pais success... ")
    return(file)
  }
  
  #return(file)
  
}
```





```{r function to add year to data frame being read in}

# This function checks if year column exists in the dataframe, and if it does then it makes sure that the year matches the year in filename.  If it doesn't then it adds the year from the name of file. 
get_year <- function(file, filename){
  # inputs : 
  # file - dataframe to be used
  # filename - the name of the file being imported
  # output : dataframe with correct year as a column
  if("year" %in% colnames(file)){
    year_in_file <- file$year %>% unique()
    #print(paste0("Making sure year in data matches year in ", filename))
    if(substr(filename,5,8)==year_in_file){
      cat("year success!")
    } else {print(paste0("DOUBLE CHECK YEAR IN ", filename))}
    return(file)
  }
  else{
    #print( paste0("Replacing missing year in ", filename))
    file$year <- substr(filename, 5,8)
    cat("year success!")
    return(file)
  }
  
  # return(file)
}

```


```{r}
# Function to get the number of years and the number of countries present in each file
get_country_dfs <- function(filename = dta_files[1]){
  cat(paste0("\nWorking on ",filename,"... "))
  filepath<- paste0("data/",filename) # look into fs
  country_df <- read_dta(filepath,encoding = "latin1") %>% 
    clean_names() %>% 
    get_country(filename = filename) %>% 
    get_year(filename = filename) #%>% 
  
  return(country_df)
}

dta_files <- list.files("data", pattern = "\\.dta$ | *_cy_")
#dta_files <- dta_files[grep(dta_files, pattern = "*_cy_")] 

file_data <- data.frame()
file_data <- rbind(file_data, data.frame(dta_files))
```
if (any(names(country) == "idnum" & any(names(country) == "idnum_14"))) {
               paste(idnum,idnum_14,sep = "_")
             }
```{r function to generate unique ids}
# Function to generate unique id's that contain year, country and observation info
making_uniqueID <- function(country) {
  country <- as.data.frame(country)
  #Removes value_recoded from (some) files as it will be added to all with join to countries
  country$value_recoded <- NA
  #Helper variables to determine what id used in data
  indx_idnum <- grep('.idnum', colnames(country))
  indx_idum <- grep('idum', colnames(country))
  indx_obsid <- grep('obsid', colnames(country))
  indx_respnum <- grep('respnum', colnames(country))
  indx_uid <- grep('uniq_id', colnames(country))
  country <- subset(country, select = -c(value_recoded)) %>%
    mutate(pais = as.character(pais)) %>%
    left_join(countries, by = "pais") %>%
    #Use file id
    mutate(.,
       idnum =
        (
          if (length(indx_uid) == 1) {
            country[[indx_uid]]
          } else if (any(names(country) == "idnum" &
                         any(names(country) == "idnum_14"))) {
            paste(idnum, idnum_14, sep = "_")
          } else if (any(names(country) == "idnum")) {
            country$idnum
          } else if (any(names(country) == "idnum_14")) {
            country$idnum_14
          } else if (any(names(country) == "id")) {
            country$id
          } else if (length(indx_respnum) == 1) {
            country[[indx_respnum]]
          } else if (length(indx_idnum) == 1) {
            country[[indx_idnum]]
          } else if (length(indx_idum) == 1) {
            country[[indx_idum]]
          } else if (length(indx_obsid) == 1) {
            country[[indx_obsid]]
          } else {""}
        )
    )  %>%
    #Adding row number to id because some files have non-unique ids
    mutate(., idnum = paste(idnum, row_number(), sep = "_")) %>%
    #Makes new column, person_id
    mutate(.,
           person_id = paste(paste(#Takes first 3 letters of country name
             value_recoded,
             #Selects last two digits of year
             substr(year, 3, 4), sep = ''),
             #Separates the country name from the year with underscore
             idnum, sep = "_"))
  
  #Converts person_id column to a character
  country <- transform(country, idnum = as.character(idnum))
  country <-
    transform(country, person_id = as.character(person_id)) %>% select(person_id, everything())
  return(country)
}

```

```{r function to generate/get weights}
gen_weights <- function(country_df) {
  #creates final output variable
  country_df$weight <- NA
  #loops through all rows and sets weight variable to ...
  #weight 1500 if possible
  #if no weight1500, then generate wt1500 from wt
  #or 1 weight then calculate wt1500 if no wt or wt15000
  for (i in 1:nrow(country_df)) {
    if (!is.na(country_df$weight1500[i])) {
      country_df$weight[i] <- country_df$weight1500[i]
    } else if (!is.na(country_df$wt[i])) {
      country_df$weight[i] <- ((country_df$wt[i] * 1500) / (nrow(
        country_df %>% filter(
          country_df$pais == country_df$pais[i] &
            country_df$year == country_df$year[i]
        ))
      ))
    } else if (is.na(country_df$weight1500[i]) &&
               is.na(country_df$wt[i])) {
      country_df$weight[i] <- ((1500) / (nrow(
        country_df %>% filter(
          country_df$pais == country_df$pais[i] &
            country_df$year == country_df$year[i]
        ))
      ))
    }
  }
  return(country_df)
}
```


```{r warning=FALSE}

country_list <- lapply(file_data$dta_files, get_country_dfs)
final_country_df <- data.frame()

# Combining the list of dataframes into one data frame.
for(i in 1:length(country_list)){
  
  print(paste0(i, "/", length(country_list)))
  country_df <- making_uniqueID(country_list[[i]]) %>% 
    select(person_id, one_of(target_vars)) %>% 
    zap_labels() %>% 
    mutate_at(vars(contains('idnum')), as.character) %>% 
    mutate_at(vars(contains('pais')), as.numeric) %>% 
    mutate_at(vars(contains('year')), as.numeric) %>% 
    mutate_at(vars(contains('clusterdesc')), as.character) 
  
  final_country_df <- bind_rows(final_country_df, country_df)
  
}

# Adding full country names to data frame.
final_country_df <- left_join(final_country_df,
                              (
                                response_labels %>%
                                  filter(column_name == "pais") %>%
                                  mutate_at(vars(("value")), as.double)
                              ),
                              by = c("pais" = "value")) %>%
  rename("country" = "label_es") %>%
  select(-c("column_name", "question_es", "value_recoded"))

# weight generation
final_country_df <- gen_weights(final_country_df)

final_country_df %>% select("person_id", "weight","wt","weight1500", everything()) %>% head()
final_country_df %>% assert(is_uniq, person_id)

```


```{r}
write_csv(final_country_df, "final_country_df.csv")
final_country_df <- read_csv("final_country_df.csv",col_types = cols(.default = col_double(),
                                                                     person_id = col_character(),
                                                                     country = col_character()))
```

Check the files that had issues with year:
```{r}
library(data.table)
install.packages("data.table")
final_country_df<-as.data.table(final_country_df)
# bra_2007_cy_por_p_v5.dta
print(names(table(read_dta("data/bra_2007_cy_por_p_v5.dta")$year)))
# guy_2008_cy_eng_p_v3.dta
print(names(table(read_dta("data/guy_2008_cy_eng_p_v3.dta")$year)))
# ury_2007_cy_spa_p.dta
print(names(table(read_dta("data/ury_2007_cy_spa_p.dta")$year)))
# ven_2007_cy_spa_p.dta
print(names(table(read_dta("data/ven_2007_cy_spa_p.dta")$year)))
```
These are okay so far--let's stick with whatever happens for year/wave until we are at a point where we can actually see data in Tableau.



