---
title: "Finding Common Questions"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

# Structure
In order to cut down on the size of the data, we are reducing the total combination of all countries to the common questions.

```{r Import libraries, message=FALSE}
library(janitor)
library(rlang)
```


LAPOP has defined which questions to inlcude. Rather than determining which questions appear across all country questionnaires, we'll do a lookup.

Using the lookup tables above, filter out the questions that are not in the list



```{r Find common questions}
#Common questions as defined by LAPOP 
common_questions <- questions_cats %>%
  select(column_name) %>%
  distinct()

#Creating a list with all the clean data frames
countries <- list(argentina_clean, belize_clean, bolivia_clean, brazil_clean, canada_clean, chile_clean, costa_clean, ecuador_clean, elsalvador_clean, guatemala_clean, guyana_clean, honduras_clean, jamaica_clean, mexico_clean, nicaragua_clean, panama_clean, paraguay_clean, peru_clean, suriname_clean, uruguay_clean, usa_clean, venezuela_clean) #colombia_clean not resolved

#Function for joining dataframes to ensure each country has only the common questions
find_common <- function(country_dfr, questions_dfr) {
  semi_join(country_dfr, questions_dfr, by = "column_name")
}

#Applying `map_dfr` to create combined dataframe
#countries_common_only <- map_dfr(countries, find_common, common_questions)

#Trying `map_dfr` on combined_clean
total_long_common <- find_common(combined_clean, common_questions) 

```
