---
title: "Widening by fewer countries"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

Ran into an issue with widening the long dataset (total_long_common), as it returned only NAs. Going to start with one country and then get bigger.
```{r}
test0 <- total_long_common %>% 
  select(country, wave, person_id_factor, weights, category_question, answer_measure) %>% 
  filter(country == "Argentina") %>% 
  pivot_wider(id_cols = person_id_factor, names_from = category_question, values_from = answer_measure)
```

Produced filtered total_long_common for analysis.
```{r}
argentina <- total_long_common %>% 
  select(country, wave, person_id, weights, category_question, answer_measure) %>% 
  filter(country == "Argentina") %>% 
  filter(person_id == 5921)
```


```{r}
test1 <- total_long_common %>% 
  select(country, wave, person_id_factor, weights, category_question, answer_measure) %>% 
  filter(country == "Bolivia") %>% 
  pivot_wider(id_cols = person_id_factor, names_from = category_question, values_from = answer_measure)
```

Using tabyl() for analysis
```{r}
total_long_common %>%
  filter(person_id_factor == "BOL04_7469") %>% 
  tabyl(category_question)
```

```{r}
total_long_common %>% 
  count(category_question) %>% 
  arrange(n)
```
This shows that there are 69 questions with varying counts (from 197,549 to 229,634)

```{r}
id_arranged <- total_long_common %>% 
  count(person_id_factor) %>% 
  arrange(n)
```

```{r}
total_long_common %>% 
  tabyl(category_question)
```




## !Don't use - Reference only
# ```{r}
# spec <- pivot_wider_spec(total_long_common, names_from = category_question, values_from = c(answer_dimension, answer_measure))
# 
# spec2 <- total_long_common %>% 
#   expand(category_question, .value = c(answer_dimension, answer_measure))
# ```
# 
# ```{r}
# spec3 <- pivot_wider_spec(total_long_common,
#                           names_from = category_question,
#                           values_from = c(answer_dimension, answer_measure)) %>%
#   expand(category_question,
#          .value = answer_measure)
# ```


